# Ingress configuration for development
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: skaffold-p-m.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: client
          servicePort: 3001
        - path: /api
          pathType: Prefix
          serviceName: server
          servicePort: 3000
        - path: /health
          pathType: Prefix
          serviceName: server
          servicePort: 3000
  tls: []

# Redis configuration for development
redis:
  persistence: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi