version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      target: production
    ports:
      - "3001:80"
    depends_on:
      - server
    restart: no

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always