apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: my-app

build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: false
  artifacts:
    - image: ghcr.io/dostapovets/mono-skaffold-nx-client
      context: .
      docker:
        dockerfile: apps/client/Dockerfile
        target: "production"
      sync:
        manual:
          - src: apps/client/**/*
            dest: .
          - src: packages/**/*
            dest: .
    - image: ghcr.io/dostapovets/mono-skaffold-nx-server
      docker:
        dockerfile: apps/server/Dockerfile
        target: "production"
      context: .  
      sync:
        manual:
          - src: apps/server/**/*
            dest: .
          - src: packages/**/*
            dest: .
deploy:
  helm:
    releases:
      - name: my-app
        chartPath: ./helm
        valuesFiles:
          - "./helm/env-values/{{ .ENV }}.yaml"
        namespace: default
        setValueTemplates:
          client.image.repository: "{{.IMAGE_REPO_ghcr_io_dostapovets_mono_skaffold_nx_client}}"
          client.image.tag: "{{.IMAGE_TAG_ghcr_io_dostapovets_mono_skaffold_nx_client}}@{{.IMAGE_DIGEST_ghcr_io_dostapovets_mono_skaffold_nx_client}}"
          server.image.repository: "{{.IMAGE_REPO_ghcr_io_dostapovets_mono_skaffold_nx_server}}"
          server.image.tag: "{{.IMAGE_TAG_ghcr_io_dostapovets_mono_skaffold_nx_server}}@{{.IMAGE_DIGEST_ghcr_io_dostapovets_mono_skaffold_nx_server}}"
# portForward:
  # Port forward the client service in dev mode
  # - resourceType: service
  #   resourceName: my-app-client
  #   namespace: default
  #   port: 3001
  #   localPort: 3001
  # Port forward the server service in dev mode
  # - resourceType: service
  #   resourceName: my-app-server
  #   namespace: default
  #   port: 3000
  #   localPort: 3000
  # Port forward the Redis master service in dev mode
  # - resourceType: service
  #   resourceName: my-app-redis-master
  #   namespace: default
  #   port: 6379
  #   localPort: 6379 

profiles:
  # Development profile
  - name: development
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: "development"
      - op: replace
        path: /build/artifacts/1/docker/target
        value: "development"

  # Staging profile
  - name: staging

  # Production profile
  - name: production
