{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client.fullname" . }}-nginx-config
  labels:
    {{- include "client.labels" . | nindent 4 }}
data:
  default.conf: |
{{ tpl ($.Files.Get "nginx/default.conf.tpl") . | indent 4 }}
{{- end }}