{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Release.Name }}-client
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;

      server_name _;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      location /api {
        proxy_pass http://{{ .Release.Name }}-server:{{ .Values.server.service.port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }
{{- end }}