apiVersion: v2
name: my-app
description: A Helm chart for the complete application
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled